name: Build & Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build Release
      run: msbuild *.sln /p:Configuration=Release /p:Platform=x64 /m
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: Release/
